name: Publish npm

on:
  release:
    type: published
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      NODE_VERSION: '12.x'
    steps:
    - name: Checkout ${{ github.ref }}
      uses: actions/checkout@v2
    - name: Use Node.js ${{ env.NODE_VERSION }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ env.NODE_VERSION }}
    - run: npm ci
    - run: npm test
    - run: npm run build
    - run: npm run bundle
    - uses: JS-DevTools/npm-publish@v1
      with:
        token: ${{ secrets.NPM_AUTH_TOKEN }}
